version: '3.8'

services:
  app:
    container_name: hackaton-converter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      API_PORT: 3000
    networks:
      - hackaton-network
      - hackaton-global

networks:
  hackaton-network:
    driver: bridge
  hackaton-global:
    external: true

volumes:
  postgres-data:
